src/Entity/Marge.php
<?php

namespace App\Entity;

use App\Repository\MargeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MargeRepository::class)]
class Marge
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $marge_achat = null;

    #[ORM\Column]
    private ?float $marge_vente = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_mise_jour = null;

    #[ORM\OneToOne(inversedBy: 'marge', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cours $cours = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMargeAchat(): ?float
    {
        return $this->marge_achat;
    }

    public function setMargeAchat(float $marge_achat): static
    {
        $this->marge_achat = $marge_achat;

        return $this;
    }

    public function getMargeVente(): ?float
    {
        return $this->marge_vente;
    }

    public function setMargeVente(float $marge_vente): static
    {
        $this->marge_vente = $marge_vente;

        return $this;
    }

    public function getDateMiseJour(): ?\DateTimeInterface
    {
        return $this->date_mise_jour;
    }

    public function setDateMiseJour(\DateTimeInterface $date_mise_jour): static
    {
        $this->date_mise_jour = $date_mise_jour;

        return $this;
    }

    public function getCours(): ?Cours
    {
        return $this->cours;
    }

    public function setCours(Cours $cours): static
    {
        $this->cours = $cours;

        return $this;
    }
}

src/Form/MargeType.php
<?php

namespace App\Form;

use App\Entity\Marge;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MargeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('marge_achat')
            ->add('marge_vente')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Marge::class,
        ]);
    }
}

src/Controller/MargeController.php
<?php

namespace App\Controller;

use App\Entity\Marge;
use App\Form\Marge1Type;
use App\Repository\MargeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/marge')]
class MargeController extends AbstractController
{
    #[Route('/', name: 'app_marge_index', methods: ['GET'])]
    public function index(MargeRepository $margeRepository): Response
    {
        return $this->render('marge/index.html.twig', [
            'marges' => $margeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_marge_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $marge = new Marge();
        $form = $this->createForm(Marge1Type::class, $marge);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($marge);
            $entityManager->flush();

            return $this->redirectToRoute('app_marge_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('marge/new.html.twig', [
            'marge' => $marge,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_marge_show', methods: ['GET'])]
    public function show(Marge $marge): Response
    {
        return $this->render('marge/show.html.twig', [
            'marge' => $marge,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_marge_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Marge $marge, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Marge1Type::class, $marge);
        $form->handleRequest($request);
        $user = $this->getUser();

        //$margeBH_achat = (($marge->getCours()->getCoursBHAchat() / $marge->getCours()->getCoursBCTAchat()) - 1) * -100;
        //$margeBH_vente = (($marge->getCours()->getCoursBHVente() / $marge->getCours()->getCoursBCTVente() ) - 1) * 100;





        if ($form->isSubmitted() && $form->isValid()) {
            $coursBH_achat = $marge->getCours()->getCoursBCTAchat() * (1 - ($marge->getMargeAchat() / 100));
            $marge->getCours()->setCoursBHAchat($coursBH_achat);

            $coursBH_vente = $marge->getCours()->getCoursBCTVente() * (1 + ($marge->getMargeVente() / 100));
            $marge->getCours()->setCoursBHVente($coursBH_vente);
            $entityManager->flush();

            return $this->redirectToRoute('app_cours_by_marche', ['id'=>$marge->getCours()->getMarche()->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('marge/edit.html.twig', [
            'marge' => $marge,
            'form' => $form,
            'user' => $user
        ]);
    }

    #[Route('/{id}', name: 'app_marge_delete', methods: ['POST'])]
    public function delete(Request $request, Marge $marge, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$marge->getId(), $request->request->get('_token'))) {
            $entityManager->remove($marge);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_marge_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/marge/_delete_form.html.twig
<form method="post" action="{{ path('app_marge_delete', {'id': marge.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ marge.id) }}">
    <button class="btn">Delete</button>
</form>

templates/marge/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/marge/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Marge index{% endblock %}

{% block body %}
    <h1>Marge index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Marge_achat</th>
                <th>Marge_vente</th>
                <th>Date_mise_jour</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for marge in marges %}
            <tr>
                <td>{{ marge.id }}</td>
                <td>{{ marge.margeAchat }}</td>
                <td>{{ marge.margeVente }}</td>
                <td>{{ marge.dateMiseJour ? marge.dateMiseJour|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_marge_show', {'id': marge.id}) }}">show</a>
                    <a href="{{ path('app_marge_edit', {'id': marge.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_marge_new') }}">Create new</a>
{% endblock %}

templates/marge/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Marge{% endblock %}

{% block body %}
    <h1>Create new Marge</h1>

    {{ include('marge/_form.html.twig') }}

    <a href="{{ path('app_marge_index') }}">back to list</a>
{% endblock %}

templates/marge/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Marge{% endblock %}

{% block body %}
    <h1>Marge</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ marge.id }}</td>
            </tr>
            <tr>
                <th>Marge_achat</th>
                <td>{{ marge.margeAchat }}</td>
            </tr>
            <tr>
                <th>Marge_vente</th>
                <td>{{ marge.margeVente }}</td>
            </tr>
            <tr>
                <th>Date_mise_jour</th>
                <td>{{ marge.dateMiseJour ? marge.dateMiseJour|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_marge_index') }}">back to list</a>

    <a href="{{ path('app_marge_edit', {'id': marge.id}) }}">edit</a>

    {{ include('marge/_delete_form.html.twig') }}
{% endblock %}