src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $coursBH_achat = null;

    #[ORM\Column]
    private ?float $coursBH_vente = null;

    #[ORM\Column(nullable: true)]
    private ?float $coursMoy = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

   
    #[ORM\Column]
    private ?int $etat = null;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    private ?Marche $marche = null;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    private ?Devise $devise = null;

    #[ORM\OneToOne(mappedBy: 'cours', cascade: ['persist', 'remove'])]
    private ?Marge $marge = null;

    #[ORM\Column]
    private ?float $coursBCT_achat = null;

    #[ORM\Column]
    private ?float $coursBCT_vente = null;

   

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCoursBHAchat(): ?float
    {
        return $this->coursBH_achat;
    }

    public function setCoursBHAchat(float $coursBH_achat): static
    {
        $this->coursBH_achat = $coursBH_achat;

        return $this;
    }

    public function getCoursBHVente(): ?float
    {
        return $this->coursBH_vente;
    }

    public function setCoursBHVente(float $coursBH_vente): static
    {
        $this->coursBH_vente = $coursBH_vente;

        return $this;
    }

    public function getCoursMoy(): ?float
    {
        return $this->coursMoy;
    }

    public function setCoursMoy(?float $coursMoy): static
    {
        $this->coursMoy = $coursMoy;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

   
    public function getEtat(): ?int
    {
        return $this->etat;
    }

    public function setEtat(int $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    public function getMarche(): ?Marche
    {
        return $this->marche;
    }

    public function setMarche(?Marche $marche): static
    {
        $this->marche = $marche;

        return $this;
    }

    public function getDevise(): ?Devise
    {
        return $this->devise;
    }

    public function setDevise(?Devise $devise): static
    {
        $this->devise = $devise;

        return $this;
    }

    public function getMarge(): ?Marge
    {
        return $this->marge;
    }

    public function setMarge(Marge $marge): static
    {
        // set the owning side of the relation if necessary
        if ($marge->getCours() !== $this) {
            $marge->setCours($this);
        }

        $this->marge = $marge;

        return $this;
    }

    public function getCoursBCTAchat(): ?float
    {
        return $this->coursBCT_achat;
    }

    public function setCoursBCTAchat(float $coursBCT_achat): static
    {
        $this->coursBCT_achat = $coursBCT_achat;

        return $this;
    }

    public function getCoursBCTVente(): ?float
    {
        return $this->coursBCT_vente;
    }

    public function setCoursBCTVente(float $coursBCT_vente): static
    {
        $this->coursBCT_vente = $coursBCT_vente;

        return $this;
    }

  
}

src/Form/CoursType.php
<?php

namespace App\Form;

use App\Entity\Cours;
use App\Entity\Devise;
use App\Entity\Marche;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class CoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('coursBH_achat')
            ->add('coursBH_vente')
            ->add('coursBCT_achat')
            ->add('coursBCT_vente')
            ->add('date',DateTimeType::class,[
                'input' => 'datetime',
        ])
            ->add('devise', EntityType::class, [
                'class' => Devise::class,
                'choice_label' => 'lib_devise',])
               // ->add('marche', EntityType::class, [
                //    'class' => Marche::class,
                 //   'choice_label' => 'type',])
            
                ->add('submit', SubmitType::class)
                ;
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cours::class,
        ]);
    }
}

src/Controller/CoursController.php
<?php

namespace App\Controller;

use App\Entity\Cours;
use App\Entity\Marge;
use App\Form\CoursType;
use App\Entity\Marche;
use App\Repository\DeviseRepository;
use App\Repository\MarcheRepository;
use App\Repository\CoursRepository;
use Twilio\Rest\Client;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;


class CoursController extends AbstractController
{
   
    #[Route('/coo', name: 'app_cours_index')]
    public function index(CoursRepository $Crepo): Response
    {
        $ccc=$Crepo->findAll();
        return $this->render('menu/index.html.twig', [
            'ccc' => $ccc,
        ]);
    }

    #[Route('/nouveau', name: 'app_cours_new', methods: ['GET', 'POST'])]
    public function new(MailerInterface $mailer,Request $request, EntityManagerInterface $entityManager,MarcheRepository $MRepo,DeviseRepository $DevRepo, CoursRepository $CRepo): Response
    {
        $marche=$MRepo->findAll();
        $devise=$DevRepo->findAll();
        $ccc= $CRepo->findAll();
        
   
       
        $user = $this->getUser();
        $cour = new Cours();

        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //email
            $email = (new Email())
            ->from('khalil.belhedi@esprit.tn')
            ->to('khalillloubelhedi@gmail.com')
            
            ->subject('Time for Symfony Mailer!')
            ->text('Sending emails is fun again!')
            ->html('<p>See Twig integration for better HTML integration!</p>');

        
           
            return $this->redirectToRoute('app_cours_new', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cours/new.html.twig', [
            'cour' => $cour,
            'form' => $form,
            'marche'=>$marche,
            'user' => $user,
            'devise' => $devise,

            'ccc' => $ccc,
            
        ]);
    }

   

    #[Route('/{id}/modifier', name: 'app_cours_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cours $cour, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_marche', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cours/edit.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }

    #[Route('supprimer/{id}', name: 'app_cours_delete', methods: ['POST'])]
    public function delete(Request $request, Cours $cour, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cour->getId(), $request->request->get('_token'))) {
            $entityManager->remove($cour);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_marche', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('marche/{id}', name: 'app_par_marche', methods: ['GET', 'POST'])]
    public function AfficheParmarche(Request $request,EntityManagerInterface $entityManager,Marche $marche,$id,DeviseRepository $DevRepo,MarcheRepository $marcheRepository,CoursRepository $coursRepository): Response
    { 

        $mm=$marcheRepository->findAll();
        $devise=$DevRepo->findAll();
        $ccc= $marche->getCours();
        
   
       
        $user = $this->getUser();
        $cour = new Cours();

        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $C = $coursRepository->findOneBy(['devise'=>$cour->getDevise()]);
            $margeBH_achat = (($cour->getCoursBHAchat() / $cour->getCoursBCTAchat()) - 1) * -100;
            $margeBH_vente = (($cour->getCoursBHVente() / $cour->getCoursBCTVente()) - 1) * 100;
            if ($C){
                $C
                    ->setCoursBHAchat($cour->getCoursBHAchat())
                    ->setCoursBHVente($cour->getCoursBHVente())
                    ->setCoursBHVente($cour->getCoursBCTAchat())
                    ->setCoursBHVente($cour->getCoursBCTVente())
                    ->setDate($cour->getDate());


                $C->getMarge()->setMargeAchat($margeBH_achat);
                $C->getMarge()->setMargeVente($margeBH_vente);
                $C->getMarge()->setDateMiseJour(new \DateTime());
            }else {
                $cour->setEtat(0);
                $cour->setMarche($marche);
                $marge = new Marge();
                $marge->setCours($cour);
                $marge->setMargeAchat($margeBH_achat);
                $marge->setMargeVente($margeBH_vente);
                $marge->setDateMiseJour(new \DateTime());
                $entityManager->persist($cour);
                $entityManager->persist($marge);
            }
            $entityManager->flush();
            return $this->redirectToRoute('app_par_marche', ['id' => $marche->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cours/new.html.twig', [
            'cour' => $cour,
            'form' => $form,
            'marche'=>$mm,
            'user' => $user,
            'devise' => $devise,
            'ccc' => $ccc,
            
        ]);
    }


}

templates/cours/_delete_form.html.twig
<form method="post" action="{{ path('app_cours_delete', {'id': cour.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cour.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cours/_form.html.twig
<div class="section-wrapper">
            <div class="container">
                {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                    <div class="row">
                        <div class="col-md-6 wow bounceInLeft">

                            <div class="form-group">
                                {{ form_widget(form.coursBH_achat, {'attr': {'class': 'form-control input-lg' , 'placeholder':'cours_BH_achat' }}) }}
                                 <h6 style="color: red"> {{ form_errors(form.coursBH_achat) }} </h6>
                            
                           
                            
                                {{ form_widget(form.coursBH_vente, {'attr': {'class': 'form-control input-lg' , 'placeholder':'cours_BH_vente' }}) }}
                                 <h6 style="color: red"> {{ form_errors(form.coursBH_vente) }} </h6>

                                {{ form_widget(form.coursBCT_achat, {'attr': {'class': 'form-control input-lg' , 'placeholder':'cours_BCT_achat' }}) }}
                                <h6 style="color: red"> {{ form_errors(form.coursBCT_achat) }} </h6>



                                {{ form_widget(form.coursBCT_vente, {'attr': {'class': 'form-control input-lg' , 'placeholder':'cours_BCT_vente' }}) }}
                                <h6 style="color: red"> {{ form_errors(form.coursBCT_vente) }} </h6>
                            
                          
                                {{ form_widget(form.date, {'attr': {'class': 'form-control input-lg' , 'placeholder':'date' }}) }}
                                 <h6 style="color: red"> {{ form_errors(form.date) }} </h6>
                           
                                {{ form_widget(form.devise, {'attr': {'class': 'form-control input-lg' , 'placeholder':'devise' }}) }}
                                 
                            
                          

                            
                            <div class="col-md-6 wow bounceInRight">
                            
                            {{ form_widget(form.submit, {'attr': {'class': 'btn btn-primary btn-block input-lg' , 'value':'SEND MESSAGE' }}) }}
                        </div>
                        </div>
                            {{ form_end(form) }}
                          </div>   

templates/cours/edit.html.twig
{% block title %}Edit Cours{% endblock %}

{% block body %}
    <h1>Edit Cours</h1>

    {{ include('cours/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_cours_index') }}">back to list</a>

    {{ include('cours/_delete_form.html.twig') }}
{% endblock %}

templates/cours/index.html.twig
{% block title %}Cours index{% endblock %}

{% block body %}
    <h1>Cours index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>CoursBH_achat</th>
                <th>CoursBH_vente</th>
                <th>CoursMoy</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cour in cours %}
            <tr>
                <td>{{ cour.id }}</td>
                <td>{{ cour.coursBHAchat }}</td>
                <td>{{ cour.coursBHVente }}</td>
                <td>{{ cour.coursMoy }}</td>
                <td>{{ cour.date ? cour.date|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_cours_show', {'id': cour.id}) }}">show</a>
                    <a href="{{ path('app_cours_edit', {'id': cour.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_cours_new') }}">Create new</a>
{% endblock %}

templates/cours/show.html.twig
{% block title %}Cours{% endblock %}

{% block body %}
    <h1>Cours</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cour.id }}</td>
            </tr>
            <tr>
                <th>CoursBH_achat</th>
                <td>{{ cour.coursBHAchat }}</td>
            </tr>
            <tr>
                <th>CoursBH_vente</th>
                <td>{{ cour.coursBHVente }}</td>
            </tr>
            <tr>
                <th>CoursMoy</th>
                <td>{{ cour.coursMoy }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ cour.date ? cour.date|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_cours_index') }}">back to list</a>

    <a href="{{ path('app_cours_edit', {'id': cour.id}) }}">edit</a>

    {{ include('cours/_delete_form.html.twig') }}
{% endblock %}